const industries = [
  { title: "Prefer not to say", id: "Prefer_not_to_say" },
  { title: "Accommodations", id: "Accommodations" },
  { title: "Accounting", id: "Accounting" },
  { title: "Advertising", id: "Advertising" },
  { title: "Aerospace", id: "Aerospace" },
  { title: "Agriculture & Agribusiness", id: "Agriculture_&_Agribusiness" },
  { title: "Air Transportation", id: "Air_Transportation" },
  { title: "Apparel & Accessories", id: "Apparel_&_Accessories" },
  { title: "Auto", id: "Auto" },
  { title: "Banking", id: "Banking" },
  { title: "Beauty & Cosmetics", id: "Beauty_&_Cosmetics" },
  { title: "Biotechnology", id: "Biotechnology" },
  { title: "Chemical", id: "Chemical" },
  { title: "Communications", id: "Communications" },
  { title: "Computer", id: "Computer" },
  { title: "Construction", id: "Construction" },
  { title: "Consulting", id: "Consulting" },
  { title: "Consumer Products", id: "Consumer_Products" },
  { title: "Education", id: "Education" },
  { title: "Electronics", id: "Electronics" },
  { title: "Employment", id: "Employment" },
  { title: "Energy", id: "Energy" },
  { title: "Entertainment & Recreation", id: "Entertainment_&_Recreation" },
  { title: "Fashion", id: "Fashion" },
  { title: "Financial Services", id: "Financial_Services" },
  { title: "Fine Arts", id: "Fine_Arts" },
  { title: "Food & Beverage", id: "Food_&_Beverage" },
  { title: "Green Technology", id: "Green_Technology" },
  { title: "Health", id: "Health" },
  { title: "Information", id: "Information" },
  { title: "Information Technology", id: "Information_Technology" },
  { title: "Insurance", id: "Insurance" },
  { title: "Journalism & News", id: "Journalism_&_News" },
  { title: "Legal Services", id: "Legal_Services" },
  { title: "Manufacturing", id: "Manufacturing" },
  { title: "Media & Broadcasting", id: "Media_&_Broadcasting" },
  { title: "Medical Devices & Supplies", id: "Medical_Devices_&_Supplies" },
  { title: "Motion Pictures & Video", id: "Motion_Pictures_&_Video" },
  { title: "Music", id: "Music" },
  { title: "Pharmaceutical", id: "Pharmaceutical" },
  { title: "Public Administration", id: "Public_Administration" },
  { title: "Public Relations", id: "Public_Relations" },
  { title: "Publishing", id: "Publishing" },
  { title: "Rail", id: "Rail" },
  { title: "Real Estate", id: "Real_Estate" },
  { title: "Retail", id: "Retail" },
  { title: "Service", id: "Service" },
  { title: "Sports", id: "Sports" },
  { title: "Technology", id: "Technology" },
  { title: "Telecommunications", id: "Telecommunications" },
  { title: "Tourism", id: "Tourism" },
  { title: "Transportation", id: "Transportation" },
  { title: "Travel", id: "Travel" },
  { title: "Utilities", id: "Utilities" },
  { title: "Video Game", id: "Video_Game" },
  { title: "Web Services", id: "Web_Services" },
  { title: "Other", id: "Other" },
];

const accommodations = [
  { title: "Hostel", id: "hostel" },
  { title: "Camping", id: "camping" },
  { title: "B&B", id: "b&b" },
  { title: "Hotel", id: "hotel" },
];

const ageGroups = [
  { title: "18-22", id: "18-22" },
  { title: "23-27", id: "23-27" },
  { title: "28-35", id: "28-35" },
  { title: "36-40", id: "36-40" },
  { title: "Over 40", id: "Over 40" },
];

const budgets = [
  { title: "$0-20 - (Shoestring)", id: "20" },
  { title: "Up to $40 - (Traveler)", id: "40" },
  { title: "Up to $60 - (Glampacker)", id: "60" },
  { title: "Over $60 - (High Flyer)", id: "+" },
];

const diets = [
  { title: "Veg/Vegan", id: "veg" },
  { title: "Fine Dining", id: "fine-dining" },
  { title: "Health nut", id: "health" },
  { title: "Not Fussed", id: "not-fussed" },
  { title: "Meat Lover", id: "meat" },
];

const genders = [
  { title: "Male", id: "male" },
  { title: "Female", id: "female" },
  { title: "Other", id: "other" },
];

const hostGenders = [
  { title: "Male", id: "male" },
  { title: "Female", id: "female" },
  { title: "Either or", id: "eitherOr" },
];

const relationshipStatuses = [
  { title: "In a relationship", id: "in-relationship" },
  { title: "Married", id: "married" },
  { title: "Single", id: "single" },
  { title: "It's complicated", id: "complicated" },
  { title: "Rather not say", id: "rather-not-say" },
];

const languages = [
  { title: "English", id: "English" },
  { title: "French", id: "French" },
  { title: "German", id: "German" },
  { title: "Italian", id: "Italian" },
  { title: "Spanish", id: "Spanish" },
  { title: "Other", id: "Other" },
];

const nationalities = [
  "Prefer not to say",
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Islands",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burma",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape-Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos Islands",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of",
  "Congo, Republic of",
  "Cook Islands",
  "Costa Rica",
  "Cote D'Ivoire",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czech_Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "England",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea Bissau",
  "Guinea Ecuatorial",
  "Guinea",
  "Guyana",
  "Haiti",
  "Heard Island And McDonald Islands",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Irag",
  "Iran",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxemburg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Islands",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic Of China",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Minquelon",
  "Saint Vincent and The Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and The South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistran",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Virgin Islands British",
  "Virgin Islands US",
  "Wales",
  "Wallis And Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const otherGenders = [
  { title: "Agender", id: "agender" },
  { title: "Androgyne", id: "androgyne" },
  { title: "Bigender", id: "bigender" },
  { title: "Female to Male", id: "female to male" },
  { title: "FTM", id: "ftm" },
  { title: "Gender Fluid", id: "gender fluid" },
  { title: "Gender Nonconforming", id: "gender nonconforming" },
  { title: "Gender Questioning", id: "gender questioning" },
  { title: "Gender Variant", id: "gender variant" },
  { title: "Genderqueer", id: "genderqueer" },
  { title: "Male to Female", id: "male to female" },
  { title: "MTF", id: "mtf" },
  { title: "Neither", id: "neither" },
  { title: "Neutrois", id: "neutrois" },
  { title: "Non-binary", id: "non-binary" },
  { title: "Other", id: "other" },
  { title: "Pangender", id: "pangender" },
  { title: "Trans", id: "trans" },
  { title: "Trans Man", id: "trans man" },
  { title: "Trans Person", id: "trans person" },
  { title: "Trans Woman", id: "trans woman" },
  { title: "Transfeminine", id: "transfeminine" },
  { title: "Transgender", id: "transgender" },
  { title: "Transgender Female", id: "transgender female" },
  { title: "Transgender Male", id: "transgender male" },
  { title: "Transgender Man", id: "transgender man" },
  { title: "Transgender Person", id: "transgender person" },
  { title: "Transgender Woman", id: "transgender woman" },
  { title: "Transmasculine", id: "transmasculine" },
  { title: "Transsexual", id: "transsexual" },
  { title: "Transsexual Female", id: "transsexual female" },
  { title: "Transsexual Male", id: "transsexual male" },
  { title: "Transsexual Man", id: "transsexual man" },
  { title: "Transsexual Person", id: "transsexual person" },
  { title: "Transsexual Woman", id: "transsexual woman" },
  { title: "Two-Spirit", id: "transsexual woman" },
];

const friendsOptions = [
  {
    title: "Lift to the Party",
    value: "lifeTo",
    index: 0,
  },
  {
    title: "Depends on the Occasion",
    value: "depends",
    index: 1,
  },
  {
    title: "Life of the Party",
    value: "lifeOf",
    index: 2,
  },
];

const strangersOptions = [
  { title: "Strongly Disagree", value: "disagree", index: 0 },
  { title: "Meh", value: "meh", index: 1 },
  { title: "Strongly Agree", value: "agree", index: 2 },
];

const attitudeOptions = [
  { title: "I stick to what I like", value: "stick", index: 0 },
  { title: "Neutral", value: "neutral", index: 1 },
  { title: "Open to trying new foods", value: "try", index: 2 },
];

const societyOptions = [
  {
    title: "Science is more important, it helps us to live better lives",
    id: "science",
  },
  { title: "They are equally important", id: "both" },
  {
    title: "Art is more important, it helps us to live happier lives",
    id: "art",
  },
];

const drinksOptions = [
  { title: "Coffee", id: "coffee" },
  { title: "Wine", id: "wine" },
  { title: "Smoothie", id: "smoothie" },
  { title: "Beer", id: "beer" },
  { title: "Kombucha", id: "kombucha" },
  { title: "Tequila", id: "tequila" },
];

const allActivities = [
  "Outdoors & Adventure",
  "Museums & Historical",
  "Sports & Live Sports",
  "Live Music",
  "Volunteering",
  "Workout & Fitness",
  "Health & Well-being",
  "Food & Drink",
  "Nightlife & Festivals",
  "Arts & Culture",
  "Shopping",
];

const general_faq = [
  {
    question: "1. What does the HipHost app do?",
    answer:
      "HipHost connects travelers to locals based on a unique matching algorithm called VelocitiTM. Our formula combines mutual demographics, interests & activities to help you meet your perfect local counterpart. Like when a friend comes to visit! Travelers on HipHost have the ability to chat, get valuable insight, and potentially meet up with hosts that will enrich their experience in a given city. In turn, Hosts benefit by earning “Connect Coins” based on a simple review system. These “Connect Coins” are converted into cash and deposited into the Host’s Paypal account (Connect Coins payout is currently disabled for trial version).",
  },
  {
    question: "2. What makes a good HipHost?",
    answer:
      "The best thing about HipHost is that it’s completely personalized. We match you up with people whose company (we feel) you’re most likely to enjoy & whose advice would be the most beneficial to you. Basically, there is no ideal HipHost candidate! Our mission is to attract as many users who are motivated to meet new and interesting people as they travel & explore the world.",
  },
  {
    question: "3. Who would enjoy using the HipHost app?",
    answer:
      "Short answer...Anyone! It is made to match anyone looking to spend time with or get advice from like-minded locals, and in turn for locals to show off the magic of their city.",
  },
  {
    question: "4. How does the matching algorithm work? ",
    answer:
      "HipHost uses a combination of metrics (machine-learning) to connect locals to travelers based on who they are and what they enjoy doing! We match up your personality style with the kinds of activities you’re looking to do and help connect the perfect counterpart in the city you’re exploring!",
  },
  {
    question: "5. How do Connect Coins work?",
    answer:
      "Connect Coins are HipHost’s in-app currency. Connect Coins allow travelers to chat with their hosts, and conversely allows the Host to benefit from his/her conversation with the traveler. The current conversion rate is 2 Connect Coins to $1.",
  },
];

const traveler_faq = [
  {
    question:
      "1. Can I match & chat with a HipHost in a city I’m not currently visiting?",
    answer:
      "Absolutely, we want to let you plan your trips ahead. Simply add the dates you’ll be in a specific city and begin matching with locals in your future destination.",
  },
  {
    question: "2. Do I get reviewed as a user? If so, why?",
    answer:
      "We want to maintain a community that has people who are active and engaged.  If users don’t get reviewed the community will lose its integrity and our users won’t get the best possible experience out of HipHost!",
  },
  {
    question: "3. Who can see my profile? ",
    answer:
      "Only those in the city you are visiting and who you are currently matched with.  Protecting our users is our number one priority.",
  },
  {
    question: "4. Do I have to pay my HipHost?",
    answer:
      "No, the payment system is based on ratings and reviews.  If your Host is trying to request payment you must report them via help@hiphost.co.za.",
  },
  {
    question: "5. Is it safe to meet up with my HipHost?",
    answer:
      "Yes, meeting with your HipHost is greatly encouraged!  It is important, however, that you meet with your host at designated HipHost locations to ensure your safety.",
  },
  {
    question:
      "6. What kind of places does HipHost designate for meeting Hosts?",
    answer:
      "These places are hand-picked by the HipHost team.  We look for central and populated areas that have well-known establishments.  For example, a Starbucks in the center of New York City.",
  },
  {
    question:
      "7. What if my host is trying to meet somewhere other than a HipHost location?",
    answer:
      "If it is the first time you are meeting with your Host and he/she is trying to meet in a non HipHost approved location, we recommend that you stop your chat and let us know by clicking the End Chat button on your current chat and entering details in the text box provided.  We will look into it and get back to you.",
  },
];

const end_chat = [
  { title: "Wasn't interested", id: "not_interested" },
  { title: "Inappropriate", id: "inappropriate" },
  { title: "Tour operator", id: "tour_operator" },
  { title: "Was a bot", id: "a_bot" },
];

export const traveler_faq_data = traveler_faq;
export const general_faq_data = general_faq;

export const end_Chat_data = end_chat;

export default {
  industries,
  ageGroups,
  accommodations,
  budgets,
  diets,
  genders,
  relationshipStatuses,
  languages,
  nationalities,
  otherGenders,
  hostGenders,
  friendsOptions,
  strangersOptions,
  attitudeOptions,
  societyOptions,
  drinksOptions,
  allActivities,
};
